# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "pg", "~> 1.1"

gem "dotenv", "~> 2.7"

gem "faraday", "~> 0.17.0"

gem "json", "~> 2.3"
